services:
    psqldb:
      image: postgres
      restart: always
      environment: 
        POSTGRES_PASSWORD: strongPassword!234
      volumes:
        - postgresdata:/var/lib/postgresql/data
      expose:
        - 5432
      ports:
        - "5432:5432"

    safe:
      image: mysafe
      build:
        context: .
        dockerfile: MySafe/Dockerfile
      expose: 
        - 8080
      ports: 
        - "8080:8080"

    mysafeclient: 
      image: mysafe-client
      build:
        context: .
        dockerfile: MySafeClient/Dockerfile
      expose: 
        - 4200
      ports: 
        - "4200:4200"

volumes:
  postgresdata:
